name: python

on: [pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image 
        run: docker build . -t docker_test

      - name: Run tests inside the container
        run: docker run docker_test pytest tests/

      - name: mypy
        run: docker run docker_test mypy src/

      - name: ruff
        run: docker run docker_test ruff check src/ tests/    
